---
- name: Prepare
  hosts: all
  tasks:
    - name: Update apt and install gpg-agent
      apt:
        name: gpg-agent
        update_cache: yes

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install docker-ce
      apt: name=docker-ce state=present

    - name: Install Docker Module for Python
      pip:
        name: "{{ item }}"
      with_items:
        - docker
        - docker-compose

    - name: Create a docker network
      docker_network:
        name: test_net
